### ISSUE TITLE
crash when rename an animal

### ISSUE THREAD

**Issue by lostopkk** [UpcraftLP/Orderly#50]
[crash-2022-09-18_17.14.20-client.txt](https://github.com/UpcraftLP/Orderly/files/9595193/crash-2022-09-18_17.14.20-client.txt)

**Comment by Jason4019** [comment]
I had the same error when using nameplates.

**Comment by Jason4019** [comment]
[00:19:51] [Render thread/WARN]: Received passengers for unknown entity
[00:19:51] [Render thread/INFO]: Loaded 603 advancements
[00:19:52] [Render thread/INFO]: Reloading entity icon resources...
[00:19:53] [Render thread/INFO]: Done!
[00:19:53] [Render thread/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[00:19:54] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IncompatibleClassChangeError: Found class net.minecraft.class_5250, but interface was expected
	at io.github.prospector.orderly.ui.DefaultUIStyle.render(DefaultUIStyle.java:48) ~[orderly-2.0-1.19.x.jar:?]
	at io.github.prospector.orderly.ui.SimpleUIStyle.renderEntity(SimpleUIStyle.java:19) ~[orderly-2.0-1.19.x.jar:?]
	at io.github.prospector.orderly.HealthBarRenderer.renderHealthBar(HealthBarRenderer.java:152) ~[orderly-2.0-1.19.x.jar:?]
	at io.github.prospector.orderly.HealthBarRenderer.lambda$render$1(HealthBarRenderer.java:54) ~[orderly-2.0-1.19.x.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap$ValueIterator.acceptOnIndex(Int2ObjectLinkedOpenHashMap.java:1733) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap$ValueIterator.acceptOnIndex(Int2ObjectLinkedOpenHashMap.java:1720) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap$MapIterator.forEachRemaining(Int2ObjectLinkedOpenHashMap.java:1259) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap$ValueIterator.forEachRemaining(Int2ObjectLinkedOpenHashMap.java:1720) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.objects.ObjectSpliterators$SpliteratorFromIterator.forEachRemaining(ObjectSpliterators.java:1194) ~[fastutil-8.5.6.jar:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at io.github.prospector.orderly.HealthBarRenderer.render(HealthBarRenderer.java:54) ~[orderly-2.0-1.19.x.jar:?]
	at net.minecraft.class_761.handler$blm000$render(class_761.java:11460) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1321) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1039) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:816) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]
[00:19:54] [Server thread/INFO]: Stopping server
[00:19:54] [Server thread/INFO]: Saving players
